### ISSUE TITLE
API redesign proposal 

### ISSUE THREAD

**Issue by matthiasschaub** [GIScience/ohsome-quality-analyst#485]
Note: In this design following endpoints where left out: `regions`, `datasets`, `fid-fields`.

## ToDos
- [x] implement `/metadata` endpoints (to be done in #545)
- [x] implement generic `/indicators` endpoint
- [x] implement generic `/reports` endpoint

## Current Design

```
api/
├─ indicator
├─ report
├─ indicators
├─ reports
├─ indicator-layer-combinations
```

### Examples

To request the Mapping Saturation Indicator

- Request URL: `https://oqt.ohsome.org/api/indicator`
- Request Body: `{"name": "MappingSaturation", "layerKey": "building_count", "bpolys": { ... }}`

To request available Indicators

- Request URL: `https://oqt.ohsome.org/api/indicators`

To request available indicator layer combinations

- Request URL: `https://oqt.ohsome.org/api/indicator-layer-combinations`

## Proposed Design

The difference is that indicator keys are part of the endpoint instead being a query key.
Also requesting `/indicators` without providing an indicator name will yield a list of indicators with metadata and valid layers attached to it.

(The same goes for the `/reports` endpoint)

```
api/
├─ indicators/
│  ├─ mapping-saturation
│  ├─ currentness
│  ├─ ...
├─ reports/
│  ├─ buildings
│  ├─ multilevel-mapping-saturation
│  ├─ ...
├─ layers
```

### Examples

To request the Mapping Saturation Indicator

- Request URL: `https://oqt.ohsome.org/api/indicators/mapping-saturation`
- Request Body: `{"layerKey": "building-count", "bpolys": { ... }}`

To request available Indicators

- Request URL: `https://oqt.ohsome.org/api/indicators`
- Response: Yields a list of indicators with metadata and valid layers

To request available indicator layer combinations

- Request URL: `https://oqt.ohsome.org/api/indicators`
- Response: Yields a list of indicators with metadata and valid layers

**Comment by joker234** [comment]
Sounds like a better design for the API :+1: 

Would there be a possibility to query multiple indicators in one query? Or should this run through a custom report?

Would there be a possibility to query multiple reports in one query?

**Comment by matthiasschaub** [comment]
We need to get:
- a list of indicators for a selected layer
- the ohsome API request parameter (filter) of a selected layer

**Comment by matthiasschaub** [comment]
Proposed Design II
```
api/
├─ indicators/
│  ├─ mapping-saturation
│  ├─ currentness
│  ├─ ...
├─ reports/
│  ├─ buildings
│  ├─ multilevel-mapping-saturation
│  ├─ ...
├─ metadata/
│  ├─ indicators
│  ├─ reports
│  ├─ layers
```

**Comment by joker234** [comment]
> Proposed Design II
> 
> ```
> api/
> ├─ indicators/
> │  ├─ mapping-saturation
> │  ├─ currentness
> │  ├─ ...
> ├─ reports/
> │  ├─ buildings
> │  ├─ multilevel-mapping-saturation
> │  ├─ ...
> ├─ metadata/
> │  ├─ indicators
> │  ├─ reports
> │  ├─ layers
> ```

This `metadata/` request then includes all topics, reports, and indicators with links between them, correct?

**Comment by matthiasschaub** [comment]
@joker234 that is correct.

**Comment by matthiasschaub** [comment]
Here is my suggestions for the response of the `/metadata` endpoint:
```json
{
  "topics": {
    "building-count": {
      "name": "Building Count",
      "description": "All buildings as defined by all objects tagged with 'building=*'.\n",
      "endpoint": "elements/count",
      "filter": "building=* and geometry:polygon",
      "indicators": [
        "mapping-saturation"
      ]
    },
    "schools": {
      "name": "Schools",
      "description": "Count of schools.",
      "endpoint": "elements/count",
      "filter": "amenity=school",
      "source": "https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dschool",
      "indicators": [
        "mapping-saturation"
      ]
    }
  },
  "indicators": {
    "mapping-saturation": {
      "name": "Mapping Saturation",
      "description": "Calculate if mapping has saturated.\nHigh saturation has been reached if the growth of the fitted curve is minimal.\n",
      "label-description": {
        "red": "No saturation identified (Saturation ≤ 30%).\n",
        "yellow": "Saturation is in progress (30% < Saturation ≤ 97%).\n",
        "green": "High saturation has been reached (97% < Saturation ≤ 100%).\n",
        "undefined": "Saturation could not be calculated.\n"
      },
      "layer-thresholds": {
        "default": [
          2,
          3,
          4,
          8
        ],
        "schools": [
          15,
          5,
          4,
          2
        ]
      }
    }
  }
}
```
I left out reports in this example. Also note that some attributes are not yet supported/implemented such as the indicator list of a topic/layer definition and the thresholds for indicators.

I ignored the `project`/`namespace` attribute for now.

**Comment by matthiasschaub** [comment]
For `metadata/indicator` see this reference implementation: #400
